[package]
name = "draft_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
gskits="0.14"
lazy_static = "1.5"
rust-htslib="0.49.0"
crossbeam = "0.8"
clap = {version="4.4", features=["derive"]}
num_cpus="1.16"
anyhow="1.0"